---
- name: Setup password file
  become: yes
  template:
    src: mosquitto.passwd.j2
    dest: "{{ mosquitto_settings.password_file }}"
  when: mosquitto_settings.password_file is defined
  notify:
    - restart mosquitto

- name: Setup local config
  become: yes
  template:
    src: mosquitto.local.conf.j2
    dest: /etc/mosquitto/conf.d/mosquitto.local.conf
  notify:
    - restart mosquitto
